### ISSUE TITLE
BDD Tesztek elkészítése

### ISSUE THREAD

**Issue by P6Z3F2** [BME-MIT-IET/iet-hf2021-sparba-qlene-sietni#13]
Kéne csinálni felhasználó barátabb teszteket, amiket mások is jobban megértenének, ezek ilyen BDD tesztek. Keressetek hozzá egy kiegészítőt (Pl.: SpecFlow) és a tesztetek inkább a minőségre és ne a mennyiségre menjen.

**Comment by benoero99** [comment]
A BDD tesztek és a dokumentáció elkészült.
