### ISSUE TITLE
Nem-funkcionális jellemzők vizsgálata

### ISSUE THREAD

**Issue by grssdm** [BME-MIT-IET/iet-hf2021-sparba-qlene-sietni#15]
Meg kellene vizsgálni a nem-funkcionális jellemzőket, pl: teljesítmény, stresszteszt..

**Comment by kalvintamas** [comment]
Megvizsgáltam a program teljesítményét memória és futásidő szempontjából több alapvető függvényen. A könyvtár futásidejei kielégítőek voltak, a program feladatinak komplexitásához képest a teljesítmény elfogadható.
