### ISSUE TITLE
SonarCloud code smell javítása

### ISSUE THREAD

**Issue by pbalazs09** [BME-MIT-IET/iet-hf2021-sparba-qlene-sietni#7]
Összesen 898 code smell van. Csökkenteni kellene a mennyiségét, amennyire csak lehetséges.

**Comment by P6Z3F2** [comment]
Átnéztem a SonarCloudon jelzett Code smelleken belül a Blocker-nél találhatókat és mindegyiknél ugyanazt a hibát jelzi. A probléma annyi lenne, hogy funkciókat adunk pár osztálynak, amit jobb lenne, ha egy abból leszármazott osztály egy külön függvényben valósítana meg. Véleményem szerint ennek a megoldása rengeteg átírást igényelne szóval ezeket részemről benne hagyhatnánk.
